version: '3.7'

services:
  vetapp:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_URL: jdbc:mysql://db_vet:3306/vet_app_db?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: 12345
    restart: always
    depends_on:
      db_vet:
        condition: service_healthy
  db_vet:
    image: mysql:8.0.30
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: vet_app_db
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10